config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  get "/home", to: "pages#home"
  get "/about", to: "pages#about", as: :about

  namespace :api do
      namespace :v1 do
        post :auth, to: "auth#create"
        resources :entries
      end
  end


  root "entries#index"

  resources :entries

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
    validates :name, :url, :username, :password, presence: true
    validate :url_must_be_valid
    belongs_to :user

    encrypts :username, deterministic: true
    encrypts :password


    private

    def url_must_be_valid
        uri = URI.parse(url) rescue nil
        unless uri&.scheme.in?(%w[http https])
            errors.add(:url, :invalid)  # will use your locale “invalid” message
        end
    end

    def self.search(params)
        data = self
        if params.present?
            if params["name"].present?
                data = self.where("name ILIKE :name", name: "%#{params[:name]}%")
            end
        else
            data = self.all
        end

        data.order(:name)
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :entries
end

app/controllers/api/v1/api_controller.rb
class Api::V1::ApiController < ApplicationController

    attr_reader :current_user

    skip_before_action :verify_authenticity_token
    before_action :set_json_format, :authenticate_token

    private

    def authenticate_token
        begin
            payload = JsonWebToken.decode(self.auth_token)
            @current_user = User.find(payload[0]["user"])

        rescue => e
            p e.to_s
            render json: {error: "401 Unauthorized"}, status: :unauthorized
        end
    end

    def auth_token
        @auth_token ||= request.headers["Authorization"]&.split(" ")&.last
        return @auth_token
    end

    def set_json_format
        request.format = :json
    end
end

app/controllers/api/v1/auth_controller.rb
class Api::V1::AuthController < Api::V1::ApiController

    skip_before_action :authenticate_token

    def create
        user = User.find_by(email: params[:email])
        if user&.valid_password?(params[:password])
            render json: {token: JsonWebToken.encode({user: user.id})}, status: :ok
        else
            render json: {errors: ["Invalid email/password"]}, status: :unauthorized
        end
    end
end

app/controllers/api/v1/entries_controller.rb
class Api::V1::EntriesController <  Api::V1::ApiController
    def index
        render json: current_user.entries
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

    before_action :authenticate_user!
    before_action :set_entry, only: %i[show destroy edit update]

    def new
        @entry = Entry.new
    end

    def show
        if @entry.present?
            respond_to do |format|
                format.html {render "entries/show"}
                format.turbo_stream {}
            end
        else
            flash[:alert] = "Entry Not Found"
            redirect_back(fallback_location: root_path)
        end

    end

    def index
        @entries = current_user.entries.search(params)
        @main_entry = @entries.first

        if @entries.count == 1 && params[:name].present?
            render turbo_stream: [
                turbo_stream.update("main-dashboard", partial: "entries/main", locals: {entry: @main_entry}),
                turbo_stream.update("search-entry", partial: "entries/entry", locals: {entry: @main_entry})
            ]
        end
    end

    def create
        @entry = current_user.entries.new(entry_params)
        if @entry.save
            @main_entry = @entry
            flash.now[:notice] = "<strong>#{@entry.name}</strong> has been saved!".html_safe
            respond_to do |format|
                format.html {redirect_to root_path}
                format.turbo_stream {}
            end

        else
            # flash[:alert] = @entry.errors.full_messages
            render :new, status: :unprocessable_content
        end
    end

    def destroy
        if @entry.destroy
            @main_entry = current_user.entries.last
            flash.now[:notice] = "<strong>#{@entry.name}</strong> has been deleted!".html_safe
            respond_to do |format|
                format.html {redirect_to :root_path}
                format.turbo_stream {}
            end
        else
            flash.now[:alert] = "Could not delete <strong>#{@entry.name}</strong>.".html_safe
            respond_to do |format|
                format.html {redirect_to :root_path}
                format.turbo_stream {}
            end
        end
    end

    def edit
    end

    def update
        if @entry.update(entry_params)
            flash.now[:notice] = "<strong>#{@entry.name}</strong> has been updated".html_safe
            respond_to do |format|
                format.html {redirect_to :root_path}
                format.turbo_stream {}
            end
        else
            render :edit, status: :unprocessable_content
        end
    end

    private

    def entry_params
        # params.require(:entry).permit(:name, :url, :username, :password)
        params.expect(entry: [:name, :url, :username, :password])
    end

    def set_entry
        @entry = current_user.entries.find_by_id(params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end

    def about
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def logo(size = "h2")
        link_to(root_path, class: "logo #{size} text-decoration-none") do
            "<i class=\"bi bi-safe-fill me-2\"></i> Safe Pass".html_safe
        end
    end

    def account_page?
        current_page?(edit_user_registration_path)
    end

    def format_time(time)
        time.strftime("%d/%M/%Y %I:%M %p")
    end

    def render_flash_stream
        turbo_stream.update("flash", partial: "shared/flash")
    end
end

app/helpers/flash_helper.rb
module FlashHelper
    def flash_class(type)
        case type
        when "notice" then "success"
        when "alert" then "danger"
        end
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/entries/_entry.html.erb
<%= link_to(entry_path(entry), class: "nav-link", data: {turbo_frame: "main-dashboard", turbo_prefetch: false}, id: dom_id(entry)) do %>
    <%= render(layout: "entries/entry_name", locals: {entry: entry}) do %>
        <%= entry.name %>
    <%end %>
<%end %>

app/views/entries/_entry_name.html.erb
<% if entry.present? %>
    <div class="d-flex align-items-center">
        <div class="entry-favicon" style="margin-right:1rem;">
            <%= image_tag("https://www.google.com/s2/favicons?domain=#{entry.url}&sz=32", alt: entry.name) %>
        </div>
        <%= yield %>
    </div>
<% end %>

app/views/entries/_main.html.erb
<div class="d-flex flex-column justify-content-between h-100">
    <div>
        <%= render(layout: "entries/entry_name", locals: { entry: entry }) do %>
            <div id="entry-name" class="w-100">
                <%= turbo_frame_tag(:entry_name, ) do %>
                    <div class="d-flex align-items-center justify-content-between flex-grow-1">
                        <h1 class="mb-0"><%= entry.name %></h1>

                        <div class="dropdown">
                            <button class="btn btn-outline-light border-0 text-dark  me-3" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="bi bi-three-dots-vertical"></i>
                            </button>
                            <ul class="dropdown-menu">
                                <li>
                                    <%= link_to(edit_entry_path(entry, input: :entry_name), class: "dropdown-item") do %>
                                        <i class="bi bi-pencil-square"></i> Edit
                                    <% end %>
                                </li>
                                <li>
                                    <%= link_to(entry_path(entry), data: { turbo_method: :delete }, class: "dropdown-item text-danger") do %>
                                        <i class="bi bi-trash3-fill"></i> Delete
                                    <% end %>
                                </li>
                            </ul>
                        </div>
                    </div>
                <% end %>
            </div>
        <% end %>
        <div class="mt-5">
            <ul class="list-group">
                <li id="entry-username" class="list-group-item">
                    <%= turbo_frame_tag(:entry_username) do %>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="form-floating w-100">
                                <%= text_field_tag(:username, entry.username, readonly: true, class: "form-control-plaintext", placeholder: "email") %>
                                <%= label_tag(:username, "Username", class: "fw-bold text-dark") %>
                            </div>
                            <div class="actions d-flex">
                                <button
                                    class="btn btn-outline-primary border-0"
                                    data-controller="clipboard"
                                    data-action="click->clipboard#copy"
                                    data-clipboard-content-param="<%= entry.username %>">
                                    <i class="bi bi-clipboard-plus"></i>
                                </button>
                                <%= link_to(edit_entry_path(entry, input: :entry_username), class: "btn btn-outline-light border-0 text-dark") do %>
                                <i class="bi bi-pencil-square"></i>
                                <% end %>
                            </div>
                        </div>

                    <% end %>
                </li>
                <li id=entry-password class="list-group-item" data-controller="toggle-password">
                    <%= turbo_frame_tag(:entry_password) do %>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="form-floating w-100">
                                <%= password_field_tag(:password, entry.password, readonly: true, class: "form-control-plaintext", placeholder: "password", data: {toggle_password_target: "input"}) %>
                                <%= label_tag(:password, "Password", class: "fw-bold text-dark") %>
                            </div>
                            <div class="actions d-flex">
                                <button
                                    class="btn btn-outline-primary border-0"
                                    data-action="click->toggle-password#toggle">
                                    <i class="bi bi-eye"></i>
                                </button>
                                <button
                                    class="btn btn-outline-primary border-0"
                                    data-controller="clipboard"
                                    data-action="click->clipboard#copy"
                                    data-clipboard-content-param="<%= entry.password %>">
                                    <i class="bi bi-clipboard-plus"></i>
                                </button>
                                <%= link_to(edit_entry_path(entry, input: :entry_password), class: "btn btn-outline-light border-0 text-dark") do %>
                                    <i class="bi bi-pencil-square"></i>
                                <% end %>
                            </div>
                        </div>

                    <% end %>
                </li>
            </ul>

            <div id="entry-url" class="mt-4">
                <%= turbo_frame_tag(:entry_url) do %>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="flex-grow-1  ms-4 ps-1">
                            <div class="fw-bold">URL</div>

                            <%= link_to(entry.url, target: :_blank, rel: "noopener noreferrer") do %>
                                <%= entry.url %> <i class="bi bi-box-arrow-up-right ms-1"></i>
                            <% end %>

                        </div>
                        <div class="actions">
                            <%= link_to(edit_entry_path(entry, input: :entry_url), class: "btn btn-outline-light border-0 text-dark me-3") do %>
                                <i class="bi bi-pencil-square"></i>
                            <% end %>
                        </div>
                    </div>

                <% end %>
            </div>


        </div>
    </div>
    <div class="text-center">
        <div>Modified at: <%= format_time(entry.updated_at) %></div>
        <div>Created at: <%= format_time(entry.created_at) %></div>
    </div>
</div>

app/views/entries/create.turbo_stream.erb
<%= render_flash_stream %>
<%= turbo_stream.append("entries-list", @entry) %>
<%= turbo_stream.update("main-dashboard") do %>
    <%= render(partial: "entries/main", locals: {entry: @entry}) %>
<% end %>

app/views/entries/destroy.turbo_stream.erb
<%= render_flash_stream %>

<% unless @entry.errors.any? %>
    <%= turbo_stream.remove(@entry) %>
    <%= turbo_stream.update("main-dashboard") do %>
        <% if current_user.entries.any? %>
            <%= render(partial: "entries/main", locals: {entry: current_user.entries.order(:name)}) %>
        <% else %>
            <%= render(html: content_tag(:nil, "No Entries", class: "h-100 w-100 d-flex align-items-center justify-content-center")) %>
        <% end %>
    <% end %>
<% end %>

app/views/entries/edit.html.erb
<%= turbo_frame_tag(params[:input]) do %>
    <%= form_with(model: @entry, class: "d-flx position-relative") do |form|  %>
        <div class="form-floating edit-name">
            <%= form.text_field(:name, placeholder: "Name", class: "form-control") %>
            <%= form.label(:name, class: "fw-bold text-dark") %>
        </div>
        <div class="form-floating edit-url">
            <%= form.text_field(:url, placeholder: "URL", class: "form-control") %>
            <%= form.label(:url, class: "fw-bold text-dark") %>
        </div>
        <div class="form-floating edit-username">
            <%= form.text_field(:username, placeholder: "Username", class: "form-control") %>
            <%= form.label(:username, class: "fw-bold text-dark") %>
        </div>

        <div class="form-floating edit-password">
            <%= form.text_field(:password, placeholder: "Password", class: "form-control") %>
            <%= form.label(:password, class: "fw-bold text-dark") %>
        </div>

        <div class="entry-edit-actions">
            <%= form.button(class: "btn btn-sm btn-outline-success rounded-circle") do %>
                <i class="bi bi-check-lg"></i>
            <% end %>
            <%= link_to(entry_path(@entry), class: "btn btn-sm btn-outline-danger rounded-circle") do %>
                <i class="bi bi-x-lg"></i>
            <% end %>
        </div>
    <% end %>
<% end %>

app/views/entries/index.html.erb
<h1>Entries</h1>

<div class="row">
    <div class="entries-actions card">
        <div class="entry-search" data-controller="search">
            <%= form_with(url: entries_path, method: :get, data: {turbo_frame: "search-entry"}, class: "position-relative") do  |form| %>
            <div class="form-floating">
                <%= form.text_field(:name, placeholder: "Search...", class: "form-control", data: {action: "input->search#toggleClearButton"}) %>
                <%= form.label(:search, for: :name) %>
            </div>
            <div class="entry-search-button">
                <%= link_to(root_path, class: "btn btn-sm btn-outline-danger rounded-circle me-2 d-none", data: {search_target: "clearButton"}) do %>
                    <i class="bi bi-x"></i>
                <% end %>
                <%= form.button(class: "btn btn-primary") do %>
                    <i class="bi bi-search"></i>
                <% end %>
            </div>
            <% end %>
        </div>
        <%= link_to("+ New Entry", new_entry_path, class: "btn btn-primary", data: {turbo_frame: "main-dashboard"}) %>
    </div>
    <div id="dashboard" class="card shadow-sm">
        <div class="entries-card">
            <div class="entries-card__sidebar">
                <%= turbo_frame_tag("search-entry") do %>
                    <div id="entries-list" class="nav flex-column">
                        <%= render(@entries) if @entries.present? %>
                    </div>
                <% end %>
            </div>
            <div class="entries-card__main">
                 <% if @entries.any? %>
                    <%= turbo_frame_tag("main-dashboard") do %>
                        <%= render(partial: "entries/main", locals: {entry: @main_entry}) %>
                    <% end %>
                <% else %>
                    <%= render(html: content_tag(:div, "No Entries", class: "h-100 w-100 d-flex align-items-center justify-content-between")) %>
                <% end %>

            </div>

        </div>
    </div>
</div>

app/views/entries/new.html.erb
<%= turbo_frame_tag("main-dashboard") do %>
    <div class="d-flex align-items-center justify-content-between">
        <h1>Create New Entry</h1>
        <%= link_to("Cancel", entries_path, class: "btn btn-sm btn-outline-danger") %>
    </div>

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <% if @entry.errors.any? %>
                        <div id="error_explanation" class="alert alert-danger" role="alert">
                            <h6>Please fix the <%= pluralize(@entry.errors.count, "error") %>  below and try again </h6>
                            <ul>
                                <% @entry.errors.messages.each do |attr, messages| %>
                                    <li>
                                        <strong><%= @entry.class.human_attribute_name(attr) %>:</strong>
                                        <%= messages.join(", ") %>
                                    </li>
                                <% end %>
                            </ul>
                        </div>
                    <% end %>
                    <%= form_with(model: @entry) do |form| %>
                        <div class="form-floating mb-3">
                            <%= form.text_field(:name, placeholder: "Name", class: "form-control") %>
                            <%= form.label(:name) %>
                        </div>
                        <div class="form-floating mb-3">
                            <%= form.text_field(:url, placeholder: "URL", class: "form-control") %>
                            <%= form.label(:url) %>
                        </div>
                        <div class="form-floating mb-3">
                            <%= form.text_field(:username, placeholder: "Username", class: "form-control") %>
                            <%= form.label(:username) %>
                        </div>

                        <div class="form-floating mb-3">
                            <%= form.text_field(:password, placeholder: "Password", class: "form-control") %>
                            <%= form.label(:password) %>
                        </div>

                        <%= form.submit("Create new entry", class: "btn btn-primary") %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>

<% end %>

app/views/entries/show.html.erb
<%#= turbo_frame_tag("main-dashboard") do %>
<!--    <h1><%#= @entry.name %></h1>-->
<!--    <div>-->
        <%#= @entry.url %>
<!--    </div>-->
<!--    <div>-->
        <%#= @entry.username %>
<!--    </div>-->
<%# end %>


<%= turbo_frame_tag("main-dashboard") do %>
    <%= render(partial: "entries/main", locals: {entry: @entry}) %>
<% end %>

app/views/entries/show.turbo_stream.erb
<%= render_flash_stream %>
<%= turbo_stream.update("main-dashboard") do %>
    <%= render(partial: "entries/main", locals: {entry: @entry}) %>
<% end %>

app/views/entries/update.turbo_stream.erb
<%= render_flash_stream %>
<%= turbo_stream.replace(@entry) %>
<%= turbo_stream.update("main-dashboard") do %>
    <%= render(partial: "entries/main", locals: {entry: @entry}) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Safe Pass App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <%= render(partial: "shared/navbar") %>

    <div id="flash">
        <%= render(partial: "shared/flash") %>
    </div>

    <div class="container">
        <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Safe Pass App Secure Authentication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
</head>

<body>
<div class="container">
    <div class="vh-100 ">
        <%= render(partial: "shared/flash") %>
        <%= render(partial: "shared/navbar") if account_page? %>
        <div class="h-100 container d-flex flex-column justify-content-center align-items-center card-auth">
            <%= link_to(root_path, class: 'navbar-brand') do %>
                <% unless account_page? %>
                    <%= logo  %>
                <% end %>

            <%end %>
            <div class="card card-auth shadow-sm w-100" >
                <div class="card m-3" style="box-shadow: none; border: none !important;" >
                    <%= yield %>
                </div>
            </div>
        </div>
    </div>

</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

app/views/pages/home.html.erb
<h1>Hello World</h1>

<button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#demo">
    Toggle
</button>
<div class="collapse mt-3" id="demo">
    <div class="card card-body">
        This content will collapse and expand.
    </div>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
    <div class="toast align-items-center text-bg-<%= flash_class(type) %> border-0 position-absolute top-0 end-0 z-1 mt-5 me-5" role="alert" aria-live="assertive" aria-atomic="true" data-controller="toast">
        <div class="d-flex">
            <div class="toast-body">
                <%= message %>
            </div>
            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light bg-body-tertiary border-bottom mb-5">
    <div class="container">
        <%#= link_to("SafePass", root_path, class: "navbar-brand") %>
        <%= logo("h5") %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMain"
                aria-controls="navbarMain" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarMain">

            <ul class="navbar-nav me-autos">
                <li class="nav-item">
                    <%= link_to "About", about_path, class: "nav-link" %>
                </li>
            </ul>


            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <% if user_signed_in? %>

                    <div class="dropdown">
                        <button class="nav-link dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-person-circle"></i>
                        </button>
                        <ul class="dropdown-menu dropdown-menu-end">
                            <li><a href="#" class="dropdown-header">Signed in as: <br><%= current_user.email %></a></li>
                            <li><%= link_to "Account", edit_user_registration_path, class: "dropdown-item" %></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><%= link_to "Sign Out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %></li>

                        </ul>
                    </div>
                <% else %>
                    <li class="nav-item">
                        <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
                    </li>
                <%end %>
            </ul>



        </div>
    </div>
</nav>